# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=x86_64
CONFIG_SOFTMMU=yes
CONFIG_SDL=yes
SDL_LIBS=-lSDL -lpthread
SDL_CFLAGS=-I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT
