# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=arm
TARGET_WORDS_BIGENDIAN=yes
CONFIG_USER_ONLY=yes
CONFIG_LINUX_USER=yes
CONFIG_SOFTFLOAT=yes
TARGET_HAS_BFLT=yes
